"""Add cascade delete to notification and push subscription

Revision ID: 07fad273aefc
Revises: c8053ae735e8
Create Date: 2025-12-14 19:30:00.058474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fad273aefc'
down_revision: Union[str, Sequence[str], None] = 'c8053ae735e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notification_user_id_fkey'), 'notification', type_='foreignkey')
    op.drop_constraint(op.f('notification_event_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('push_subscription_user_id_fkey'), 'push_subscription', type_='foreignkey')
    op.create_foreign_key(None, 'push_subscription', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'push_subscription', type_='foreignkey')
    op.create_foreign_key(op.f('push_subscription_user_id_fkey'), 'push_subscription', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_event_id_fkey'), 'notification', 'event', ['event_id'], ['id'])
    op.create_foreign_key(op.f('notification_user_id_fkey'), 'notification', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
