"""Consolidated initial migration

Revision ID: 164c04db699d
Revises: 
Create Date: 2025-11-16 16:11:39.688256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '164c04db699d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('dominant_foot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='athletegender'), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('club_affiliation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secondary_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='athletestatus'), nullable=False),
    sa.Column('registration_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_category', sa.Enum('youth', 'senior', 'trial', 'return_player', name='registrationcategory'), nullable=True),
    sa.Column('player_registration_status', sa.Enum('new', 'transfer', 'return_player', 'guest', name='playerregistrationstatus'), nullable=True),
    sa.Column('preferred_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('desired_shirt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_dominant_foot'), 'athlete', ['dominant_foot'], unique=False)
    op.create_index(op.f('ix_athlete_email'), 'athlete', ['email'], unique=False)
    op.create_index(op.f('ix_athlete_gender'), 'athlete', ['gender'], unique=False)
    op.create_index(op.f('ix_athlete_phone'), 'athlete', ['phone'], unique=False)
    op.create_index(op.f('ix_athlete_player_registration_status'), 'athlete', ['player_registration_status'], unique=False)
    op.create_index(op.f('ix_athlete_primary_position'), 'athlete', ['primary_position'], unique=False)
    op.create_index(op.f('ix_athlete_registration_category'), 'athlete', ['registration_category'], unique=False)
    op.create_index(op.f('ix_athlete_registration_year'), 'athlete', ['registration_year'], unique=False)
    op.create_index(op.f('ix_athlete_secondary_position'), 'athlete', ['secondary_position'], unique=False)
    op.create_index(op.f('ix_athlete_status'), 'athlete', ['status'], unique=False)
    op.create_index(op.f('ix_athlete_team_id'), 'athlete', ['team_id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coach_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_age_category'), 'team', ['age_category'], unique=False)
    op.create_index(op.f('ix_team_created_by_id'), 'team', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_table('testdefinition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'COACH', 'ATHLETE', name='userrole'), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('athlete_status', sa.Enum('INCOMPLETE', 'PENDING', 'APPROVED', 'REJECTED', name='userathleteapprovalstatus'), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_athlete_id'), 'user', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('assessmentsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('athlete_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_group_created_by_id'), 'athlete_group', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_athlete_group_name'), 'athlete_group', ['name'], unique=False)
    op.create_table('athletedetail',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_guardian_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_guardian_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_guardian_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medical_allergies_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medical_conditions_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physician_name_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physician_phone_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    op.create_table('athletedocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athletedocument_athlete_id'), 'athletedocument', ['athlete_id'], unique=False)
    op.create_table('athletepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athletepayment_athlete_id'), 'athletepayment', ['athlete_id'], unique=False)
    op.create_table('coachteamlink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'COMPLETED', name='eventstatus'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('push_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_created_at'), 'event', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_created_by_id'), 'event', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_event_team_id'), 'event', ['team_id'], unique=False)
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscription_user_id'), 'push_subscription', ['user_id'], unique=True)
    op.create_table('report_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('GAME', 'REPORT_CARD', name='reportsubmissiontype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reportsubmissionstatus'), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('opponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_rating', sa.Integer(), nullable=True),
    sa.Column('physical_rating', sa.Integer(), nullable=True),
    sa.Column('training_rating', sa.Integer(), nullable=True),
    sa.Column('match_rating', sa.Integer(), nullable=True),
    sa.Column('general_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_submission_athlete_id'), 'report_submission', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_report_submission_created_at'), 'report_submission', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_submission_submitted_by_id'), 'report_submission', ['submitted_by_id'], unique=False)
    op.create_index(op.f('ix_report_submission_team_id'), 'report_submission', ['team_id'], unique=False)
    op.create_table('event_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'CONFIRMED', 'DECLINED', 'MAYBE', name='participantstatus'), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_participant_athlete_id'), 'event_participant', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_event_participant_event_id'), 'event_participant', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_participant_user_id'), 'event_participant', ['user_id'], unique=False)
    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['athlete_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_membership_athlete_id'), 'group_membership', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_group_membership_group_id'), 'group_membership', ['group_id'], unique=False)
    op.create_table('match_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('report_submission_id', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('competition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('shootout_attempts', sa.Integer(), nullable=False),
    sa.Column('shootout_goals', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['report_submission_id'], ['report_submission.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_stat_athlete_id'), 'match_stat', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_match_stat_match_date'), 'match_stat', ['match_date'], unique=False)
    op.create_index(op.f('ix_match_stat_report_submission_id'), 'match_stat', ['report_submission_id'], unique=False)
    op.create_index(op.f('ix_match_stat_team_id'), 'match_stat', ['team_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_event_id'), 'notification', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('sessionresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessmentsession.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['testdefinition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionresult')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_event_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_match_stat_team_id'), table_name='match_stat')
    op.drop_index(op.f('ix_match_stat_report_submission_id'), table_name='match_stat')
    op.drop_index(op.f('ix_match_stat_match_date'), table_name='match_stat')
    op.drop_index(op.f('ix_match_stat_athlete_id'), table_name='match_stat')
    op.drop_table('match_stat')
    op.drop_index(op.f('ix_group_membership_group_id'), table_name='group_membership')
    op.drop_index(op.f('ix_group_membership_athlete_id'), table_name='group_membership')
    op.drop_table('group_membership')
    op.drop_index(op.f('ix_event_participant_user_id'), table_name='event_participant')
    op.drop_index(op.f('ix_event_participant_event_id'), table_name='event_participant')
    op.drop_index(op.f('ix_event_participant_athlete_id'), table_name='event_participant')
    op.drop_table('event_participant')
    op.drop_index(op.f('ix_report_submission_team_id'), table_name='report_submission')
    op.drop_index(op.f('ix_report_submission_submitted_by_id'), table_name='report_submission')
    op.drop_index(op.f('ix_report_submission_created_at'), table_name='report_submission')
    op.drop_index(op.f('ix_report_submission_athlete_id'), table_name='report_submission')
    op.drop_table('report_submission')
    op.drop_index(op.f('ix_push_subscription_user_id'), table_name='push_subscription')
    op.drop_table('push_subscription')
    op.drop_index(op.f('ix_event_team_id'), table_name='event')
    op.drop_index(op.f('ix_event_created_by_id'), table_name='event')
    op.drop_index(op.f('ix_event_created_at'), table_name='event')
    op.drop_table('event')
    op.drop_table('coachteamlink')
    op.drop_index(op.f('ix_athletepayment_athlete_id'), table_name='athletepayment')
    op.drop_table('athletepayment')
    op.drop_index(op.f('ix_athletedocument_athlete_id'), table_name='athletedocument')
    op.drop_table('athletedocument')
    op.drop_table('athletedetail')
    op.drop_index(op.f('ix_athlete_group_name'), table_name='athlete_group')
    op.drop_index(op.f('ix_athlete_group_created_by_id'), table_name='athlete_group')
    op.drop_table('athlete_group')
    op.drop_table('assessmentsession')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_athlete_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('testdefinition')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_created_by_id'), table_name='team')
    op.drop_index(op.f('ix_team_age_category'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_athlete_team_id'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_status'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_secondary_position'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_registration_year'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_registration_category'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_primary_position'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_player_registration_status'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_phone'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_gender'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_email'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_dominant_foot'), table_name='athlete')
    op.drop_table('athlete')
    # ### end Alembic commands ###
