"""Initial migration

Revision ID: 5c1b52d75a2b
Revises: 
Create Date: 2025-11-03 18:12:50.657138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c1b52d75a2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'athlete_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('INCOMPLETE', 'PENDING', 'APPROVED', 'REJECTED', name='userathleteapprovalstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'incomplete'"))
    op.alter_column('user', 'rejection_reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rejection_reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'athlete_status',
               existing_type=sa.Enum('INCOMPLETE', 'PENDING', 'APPROVED', 'REJECTED', name='userathleteapprovalstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'incomplete'"))
    # ### end Alembic commands ###
