"""Create initial tables

Revision ID: c173f595d77d
Revises: 
Create Date: 2025-11-26 16:16:03.176867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'c173f595d77d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('dominant_foot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='athletegender'), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('club_affiliation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secondary_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='athletestatus'), nullable=False),
    sa.Column('registration_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_category', sa.Enum('youth', 'senior', 'trial', 'return_player', name='registrationcategory'), nullable=True),
    sa.Column('player_registration_status', sa.Enum('new', 'transfer', 'return_player', 'guest', name='playerregistrationstatus'), nullable=True),
    sa.Column('preferred_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('desired_shirt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_dominant_foot'), ['dominant_foot'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_player_registration_status'), ['player_registration_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_primary_position'), ['primary_position'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_registration_category'), ['registration_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_registration_year'), ['registration_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_secondary_position'), ['secondary_position'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_team_id'), ['team_id'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coach_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_age_category'), ['age_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=False)

    op.create_table('testdefinition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'COACH', 'ATHLETE', name='userrole'), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('athlete_status', sa.Enum('INCOMPLETE', 'PENDING', 'APPROVED', 'REJECTED', name='userathleteapprovalstatus'), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_last_login_at'), ['last_login_at'], unique=False)

    op.create_table('assessmentsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessmentsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessmentsession_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('athlete_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_group_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_group_name'), ['name'], unique=False)

    op.create_table('athletedetail',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_guardian_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_guardian_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_guardian_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medical_allergies_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medical_conditions_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physician_name_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physician_phone_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    op.create_table('athletedocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athletedocument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athletedocument_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('athletepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athletepayment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athletepayment_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('coachteamlink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', app.db.types.SafeDate(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('start_time', app.db.types.SafeTime(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'COMPLETED', name='eventstatus'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('push_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_team_id'), ['team_id'], unique=False)

    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=True)

    op.create_table('report_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('GAME', 'REPORT_CARD', name='reportsubmissiontype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reportsubmissionstatus'), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('opponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_rating', sa.Integer(), nullable=True),
    sa.Column('physical_rating', sa.Integer(), nullable=True),
    sa.Column('training_rating', sa.Integer(), nullable=True),
    sa.Column('match_rating', sa.Integer(), nullable=True),
    sa.Column('general_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_submission_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_submission_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_submission_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_submission_submitted_by_id'), ['submitted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_submission_team_id'), ['team_id'], unique=False)

    op.create_table('team_combine_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('sitting_height_cm', sa.Float(), nullable=True),
    sa.Column('standing_height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('split_10m_s', sa.Float(), nullable=True),
    sa.Column('split_20m_s', sa.Float(), nullable=True),
    sa.Column('split_35m_s', sa.Float(), nullable=True),
    sa.Column('yoyo_distance_m', sa.Float(), nullable=True),
    sa.Column('jump_cm', sa.Float(), nullable=True),
    sa.Column('max_power_kmh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_combine_metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_combine_metric_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_combine_metric_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_combine_metric_recorded_by_id'), ['recorded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_combine_metric_team_id'), ['team_id'], unique=False)

    op.create_table('team_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_post_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_post_team_id'), ['team_id'], unique=False)

    op.create_table('event_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'CONFIRMED', 'DECLINED', 'MAYBE', name='participantstatus'), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participant_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participant_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participant_user_id'), ['user_id'], unique=False)

    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['athlete_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_membership_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_membership_group_id'), ['group_id'], unique=False)

    op.create_table('match_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('report_submission_id', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('competition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('shootout_attempts', sa.Integer(), nullable=False),
    sa.Column('shootout_goals', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['report_submission_id'], ['report_submission.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_stat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_stat_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_stat_match_date'), ['match_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_stat_report_submission_id'), ['report_submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_stat_team_id'), ['team_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('sessionresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessmentsession.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['testdefinition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionresult')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_event_id'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('match_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_stat_team_id'))
        batch_op.drop_index(batch_op.f('ix_match_stat_report_submission_id'))
        batch_op.drop_index(batch_op.f('ix_match_stat_match_date'))
        batch_op.drop_index(batch_op.f('ix_match_stat_athlete_id'))

    op.drop_table('match_stat')
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_membership_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_membership_athlete_id'))

    op.drop_table('group_membership')
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_participant_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_participant_athlete_id'))

    op.drop_table('event_participant')
    with op.batch_alter_table('team_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_post_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_post_created_at'))
        batch_op.drop_index(batch_op.f('ix_team_post_author_id'))

    op.drop_table('team_post')
    with op.batch_alter_table('team_combine_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_combine_metric_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_combine_metric_recorded_by_id'))
        batch_op.drop_index(batch_op.f('ix_team_combine_metric_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_team_combine_metric_athlete_id'))

    op.drop_table('team_combine_metric')
    with op.batch_alter_table('report_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_submission_team_id'))
        batch_op.drop_index(batch_op.f('ix_report_submission_submitted_by_id'))
        batch_op.drop_index(batch_op.f('ix_report_submission_created_at'))
        batch_op.drop_index(batch_op.f('ix_report_submission_athlete_id'))
        batch_op.drop_index(batch_op.f('ix_report_submission_approved_by_id'))

    op.drop_table('report_submission')
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))

    op.drop_table('push_subscription')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_team_id'))
        batch_op.drop_index(batch_op.f('ix_event_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_event_coach_id'))

    op.drop_table('event')
    op.drop_table('coachteamlink')
    with op.batch_alter_table('athletepayment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletepayment_athlete_id'))

    op.drop_table('athletepayment')
    with op.batch_alter_table('athletedocument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletedocument_athlete_id'))

    op.drop_table('athletedocument')
    op.drop_table('athletedetail')
    with op.batch_alter_table('athlete_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_group_name'))
        batch_op.drop_index(batch_op.f('ix_athlete_group_created_by_id'))

    op.drop_table('athlete_group')
    with op.batch_alter_table('assessmentsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessmentsession_athlete_id'))

    op.drop_table('assessmentsession')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_last_login_at'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_athlete_id'))

    op.drop_table('user')
    op.drop_table('testdefinition')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_name'))
        batch_op.drop_index(batch_op.f('ix_team_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_team_age_category'))

    op.drop_table('team')
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_team_id'))
        batch_op.drop_index(batch_op.f('ix_athlete_status'))
        batch_op.drop_index(batch_op.f('ix_athlete_secondary_position'))
        batch_op.drop_index(batch_op.f('ix_athlete_registration_year'))
        batch_op.drop_index(batch_op.f('ix_athlete_registration_category'))
        batch_op.drop_index(batch_op.f('ix_athlete_primary_position'))
        batch_op.drop_index(batch_op.f('ix_athlete_player_registration_status'))
        batch_op.drop_index(batch_op.f('ix_athlete_phone'))
        batch_op.drop_index(batch_op.f('ix_athlete_gender'))
        batch_op.drop_index(batch_op.f('ix_athlete_email'))
        batch_op.drop_index(batch_op.f('ix_athlete_dominant_foot'))

    op.drop_table('athlete')
    # ### end Alembic commands ###
