"""Add cascade delete to EventParticipant foreign keys

Revision ID: c8053ae735e8
Revises: e1e7f8d5b9aa
Create Date: 2025-12-14 19:25:49.078559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c8053ae735e8"
down_revision: Union[str, Sequence[str], None] = "e1e7f8d5b9aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("event_participant_athlete_id_fkey"),
        "event_participant",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("event_participant_user_id_fkey"), "event_participant", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("event_participant_event_id_fkey"), "event_participant", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "event_participant", "event", ["event_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "event_participant", "athlete", ["athlete_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "event_participant", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "report_submission",
        "coach_report",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "report_submission",
        "coach_report",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "event_participant", type_="foreignkey")
    op.drop_constraint(None, "event_participant", type_="foreignkey")
    op.drop_constraint(None, "event_participant", type_="foreignkey")
    op.create_foreign_key(
        op.f("event_participant_event_id_fkey"),
        "event_participant",
        "event",
        ["event_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("event_participant_user_id_fkey"),
        "event_participant",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("event_participant_athlete_id_fkey"),
        "event_participant",
        "athlete",
        ["athlete_id"],
        ["id"],
    )
    # ### end Alembic commands ###
