"""Add status and approval to combine metrics

Revision ID: d7f187e5842c
Revises: c173f595d77d
Create Date: 2025-11-26 21:50:30.846165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f187e5842c'
down_revision: Union[str, Sequence[str], None] = 'c173f595d77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS event_team_link")
    with op.batch_alter_table('team_combine_metric', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='combinemetricstatus'),
                nullable=False,
                server_default='PENDING',
            )
        )
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_team_combine_metric_status'), ['status'], unique=False)
        batch_op.create_foreign_key(
            "fk_team_combine_metric_approved_by_id_user",
            "user",
            ["approved_by_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_combine_metric', schema=None) as batch_op:
        batch_op.drop_constraint("fk_team_combine_metric_approved_by_id_user", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_team_combine_metric_status'))
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('status')

    op.create_table('event_team_link',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'team_id')
    )
    # ### end Alembic commands ###
